-- ============================================
-- DATABASE: HOTELRESERVATIONSYSTEM
-- ============================================

CREATE DATABASE IF NOT EXISTS HOTELRESERVATIONSYSTEM;
USE HOTELRESERVATIONSYSTEM;

-- ============================================
-- TABLE: CUSTOMER
-- ============================================
CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(15) NOT NULL
);

select * from CUSTOMER;
-- ============================================
-- TABLE: ROOM
-- ============================================
CREATE TABLE IF NOT EXISTS ROOM (
    ROOM_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROOM_TYPE ENUM('STANDARD', 'DELUXE', 'SUITE') NOT NULL,
    AVAILABLE BOOLEAN NOT NULL DEFAULT TRUE,
    PRICE_PER_DAY DOUBLE NOT NULL CHECK (PRICE_PER_DAY > 0)
);

-- ============================================
-- TABLE: BOOKING
-- ============================================
CREATE TABLE IF NOT EXISTS BOOKING (
    BOOKING_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    ROOM_ID INT NOT NULL,
    CHECK_IN_DATE DATE NOT NULL,
    CHECK_OUT_DATE DATE NOT NULL,
    TOTAL_AMOUNT DOUBLE NOT NULL CHECK (TOTAL_AMOUNT >= 0),
    STATUS ENUM('CREATED','CONFIRMED','CANCELLED','COMPLETED') NOT NULL DEFAULT 'CREATED',
    CONSTRAINT FK_BOOKING_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER(CUSTOMER_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_BOOKING_ROOM FOREIGN KEY (ROOM_ID)
        REFERENCES ROOM(ROOM_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT CHK_CHECKOUT_AFTER_CHECKIN CHECK (CHECK_OUT_DATE > CHECK_IN_DATE)
);


select * from BOOKING;






-- ============================================
-- TABLE: PAYMENT
-- ============================================
CREATE TABLE IF NOT EXISTS PAYMENT (
    PAYMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    BOOKING_ID INT NOT NULL,
    AMOUNT DOUBLE NOT NULL CHECK (AMOUNT >= 0),
    STATUS ENUM('PENDING','SUCCESS','FAILED','REFUNDED') NOT NULL DEFAULT 'PENDING',
    PAYMENT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PAYMENT_BOOKING FOREIGN KEY (BOOKING_ID)
        REFERENCES BOOKING(BOOKING_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
